CREATE TABLE egresos_estatales (
	CVEGEO integer,
	NomEstado varchar(255), 
	ee1 double precision, 
	ee2 double precision,
	ee3 double precision,
	ee4 double precision,
	ee5 double precision,
	ee6 double precision,
	ee7 double precision,
	ee8 double precision,
	ee9 double precision,
	ee10 double precision,
	ee11 double precision,
	ee12 double precision,
	ee13 double precision,
	ee14 double precision,
	ee15 double precision,
	ee16 double precision,
	ee17 double precision,
	ee18 double precision,
	ee19 double precision,
	ee20 double precision,
	ee21 double precision,
	ee22 double precision,
	ee23 double precision,
	ee24 double precision,
	ee25 double precision,
	ee26 double precision,
	ee27 double precision,
	ee28 double precision,
	ee29 double precision,
	ee30 double precision,
	ee31 double precision,
	ee32 double precision,
	ee33 double precision,
	ee34 double precision,
	ee35 double precision
);

CREATE TABLE egresos_municipales (
	CveEstado integer,
	NomEstado varchar(255),
	CveMun integer,
	NomMun varchar(255), 
	em1 double precision,
	em2 double precision,
	em3 double precision,
	em4 double precision,
	em5 double precision,
	em6 double precision,
	em7 double precision,
	em8 double precision,
	em9 double precision,
	em10 double precision,
	em11 double precision,
	em12 double precision,
	em13 double precision,
	em14 double precision,
	em15 double precision,
	em16 double precision,
	em17 double precision,
	em18 double precision,
	em19 double precision,
	em20 double precision,
	em21 double precision,
	em22 double precision,
	em23 double precision,
	em24 double precision,
	em25 double precision,
	em26 double precision,
	em27 double precision,
	em28 double precision,
	em29 double precision,
	em30 double precision,
	em31 double precision,
	em32 double precision
);

CREATE TABLE egresos_porcentajes (
	CveEstado integer,
	NomEstado varchar(255),
	em4 double precision,
	em7 double precision,
	em10 double precision,
	em13 double precision,
	em16 double precision,
	em19 double precision,
	em22 double precision,
	em25 double precision,
	em28 double precision,
	em31 double precision
);

CREATE TABLE egresos_porcentajes_1000 (
	CveEstado integer,
	NomEstado varchar(255),
	em5 double precision,
	em8 double precision,
	em11 double precision,
	em14 double precision,
	em17 double precision,
	em20 double precision,
	em23 double precision,
	em26 double precision,
	em29 double precision,
	em32 double precision
);

copy egresos_estatales FROM '/var/www/emus-itdp/api/database/egresos/Egresos-Estatales-Limpio_V2.csv' DELIMITER ',' CSV;
copy egresos_municipales FROM '/var/www/emus-itdp/api/database/egresos/Egresos-Municipales-Limpio_V2.csv' DELIMITER ',' CSV;
copy egresos_porcentajes FROM '/var/www/emus-itdp/api/database/egresos/Egresos-Porcentajes.csv' DELIMITER ',' CSV;
copy egresos_porcentajes_1000 FROM '/var/www/emus-itdp/api/database/egresos/Egresos-Porcentajes-1000.csv' DELIMITER ',' CSV;
